#!/bin/sh

cd $SNAP/app/

# first start, copy plugins
if [ ! -e ~/appleJuice/gui/plugins ]; then
  mkdir -p ~/appleJuice/gui/plugins
  cp ./plugins/*.jar ~/appleJuice/gui/plugins/
fi

java -jar AJCoreGUI.jar "${@}"
