version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directories:
      - /
      - /modules/ajcorefassade
      - /modules/tklcontrols
      - /modules/AJCoreGUI
      - /modules/logviewer
      - /modules/versionchecker
      - /modules/standardpwdlpolicy
      - /modules/speedgraph
    schedule:
      interval: weekly
