/*
 * Copyright 2006 TKLSoft.de   All rights reserved.
 */
package de.applejuicenet.client.fassade.shared;

public interface StringConstants
{
   String AND                                 = "&";
   String AND_SHAREDDIRECTORY                 = "&sharedirectory";
   String AND_SHARESUB                        = "&sharesub";
   String GLEICH                              = "=";
   String UTF_8                               = "UTF-8";
   String FALSE                               = "false";
   String SET_SETTINGS_URL                    = "/function/setsettings?password=";
   String AND_PWDL                            = "&powerdownload=";
   String SET_PWDL_URL                        = "/function/setpowerdownload?password=";
   String GET_INFORMATION_URL                 = "/xml/information.xml?password=";
   String UPLOAD_SPEED                        = "uploadspeed";
   String DOWNLOAD_SPEED                      = "downloadspeed";
   String CREDITS                             = "credits";
   String SESSION_UPLOAD                      = "sessionupload";
   String SESSION_DOWNLOAD                    = "sessiondownload";
   String OPEN_CONNECTIONS                    = "openconnections";
   String MAX_UPLOAD_POSITIONS                = "maxuploadpositions";
   String NAME                                = "name";
   String HOST                                = "host";
   String PORT                                = "port";
   String LAST_SEEN                           = "lastseen";
   String CONNECTIONTRY                       = "connectiontry";
   String WELCOMEMESSAGE                      = "welcomemessage";
   String SEARCHENTRY                         = "searchentry";
   String SEARCH                              = "search";
   String OBJECT                              = "object";
   String NETWORKINFO                         = "networkinfo";
   String INFORMATION                         = "information";
   String SERVER                              = "server";
   String UPLOAD                              = "upload";
   String DOWNLOAD                            = "download";
   String USER                                = "user";
   String CHECKSUM                            = "checksum";
   String SEARCHID                            = "searchid";
   String TRUE                                = "true";
   String RUNNING                             = "running";
   String SUMSEARCHES                         = "sumsearches";
   String FOUNDFILES                          = "foundfiles";
   String OPENSEARCHES                        = "opensearches";
   String SEARCHTEXT                          = "searchtext";
   String READY                               = "ready";
   String TARGETDIRECTORY                     = "targetdirectory";
   String TEMPORARYFILENUMBER                 = "temporaryfilenumber";
   String HASH                                = "hash";
   String SIZE                                = "size";
   String DOWNLOADID                          = "downloadid";
   String ACTUALDOWNLOADPOSITION              = "actualdownloadposition";
   String SOURCE                              = "source";
   String NICKNAME                            = "nickname";
   String FILENAME                            = "filename";
   String DOWNLOADTO                          = "downloadto";
   String POWERDOWNLOAD                       = "powerdownload";
   String QUEUEPOSITION                       = "queueposition";
   String DOWNLOADFROM                        = "downloadfrom";
   String ID                                  = "id";
   String _0_0_0_0                            = "0.0.0.0";
   String VERSION                             = "version";
   String OPERATINGSYSTEM                     = "operatingsystem";
   String LOADED                              = "loaded";
   String LASTCONNECTION                      = "lastconnection";
   String NICK                                = "nick";
   String SPEED                               = "speed";
   String UPLOADTO                            = "uploadto";
   String ACTUALUPLOADPOSITION                = "actualuploadposition";
   String UPLOADFROM                          = "uploadfrom";
   String PRIORITY                            = "priority";
   String DIRECTSTATE                         = "directstate";
   String STATUS                              = "status";
   String SHAREID                             = "shareid";
   String CONNECTEDSINCE                      = "connectedsince";
   String CONNECTEDWITHSERVERID               = "connectedwithserverid";
   String TRYCONNECTTOSERVER                  = "tryconnecttoserver";
   String IP                                  = "ip";
   String FIREWALLED                          = "firewalled";
   String FILESIZE                            = "filesize";
   String FILES                               = "files";
   String USERS                               = "users";
   String QUESTIONMARK                        = "?";
   String MODE_ZIP                            = "mode=zip";
   String TIMESTAMP                           = "&timestamp=";
   String PASSWORD                            = "password=";
   String TIME                                = "time";
   String HTML_START                          = "<html>";
   String HTML_END                            = "</html>";
   String POINT                               = ".";
   String EMPTY                               = "";
   String COMMA                               = ",";
   String SPACE                               = " ";
   String TWO_QUESTIONMARKS                   = " ??";
   String TB                                  = " TB";
   String GB                                  = " GB";
   String MB                                  = " MB";
   String _0_00_MB                            = "0,00 MB";
   String AND_ID                              = "&id=";
   String XML_USERPARTLIST_XML_DOWNLOAD       = "/xml/downloadpartlist.xml?";
   String XML_USERPARTLIST_XML_DOWNLOADSOURCE = "/xml/userpartlist.xml?";
   String PASSWORD_GLEICH                     = "password=";
   String PART                                = "part";
   String FILEINFORMATION                     = "fileinformation";
   String TYPE                                = "type";
   String FROMPOSITION                        = "fromposition";
   String MODE_ZIP_AND                        = "mode=zip&";
   String SEPERATOR                           = "seperator";
   String FILESYSTEM                          = "filesystem";
   String XML_INFORMATION_XML_PASSWORD        = "/xml/information.xml?password=";
   String WINDOWS_NT                          = "Windows NT";
   String LINUX                               = "Linux";
   String WIN32                               = "Win32";
   String SESSION                             = "session";
   String SHAREMODE                           = "sharemode";
   String DIRECTORY                           = "directory";
   String TEMPORARYDIRECTORY                  = "temporarydirectory";
   String INCOMINGDIRECTORY                   = "incomingdirectory";
   String MAXNEWCONNECTIONSPERTURN            = "maxnewconnectionsperturn";
   String SPEEDPERSLOT                        = "speedperslot";
   String AUTOCONNECT                         = "autoconnect";
   String MAXSOURCESPERFILE                   = "maxsourcesperfile";
   String MAXCONNECTIONS                      = "maxconnections";
   String MAXDOWNLOAD                         = "maxdownload";
   String MAXUPLOAD                           = "maxupload";
   String XMLPORT                             = "xmlport";
   String SHARE                               = "share";
   String SEARCHCOUNT                         = "searchcount";
   String ASKCOUNT                            = "askcount";
   String LASTASKED                           = "lastasked";
   String SHORTFILENAME                       = "shortfilename";
   String HTTP_1_1_200_OK                     = "HTTP/1.1 200 OK";
   String INVALID_ID                          = "invalid id";
   String WRONGPASSWORD                       = "/wrongpassword";
   String CONTENT_LENGTH                      = "Content-Length:";
   String OK                                  = "ok";
   String HOST_DOUBLEPOINT                    = "host: ";
   String _20                                 = "%20";
   String HTTP_1_1                            = " HTTP/1.1";
   String POST_EMPTY                          = "POST ";
   String GET_EMTPY                           = "GET ";
}
