name: applejuice-gui
title: appleJuice GUI
summary: appleJuice GUI for appleJuice Client
description: appleJuice GUI for appleJuice Client
version: 0.85.1
icon: snap/gui/applejuice-gui.png
license: GPL-2.0

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

layout:
  /usr/bin/xprop:
    bind-file: $SNAP/usr/bin/xprop

hooks:
  configure:
    plugs: [ home ]

apps:
  ajgui:
    command: $SNAP/app/launcher
    extensions:
      - gnome
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - desktop
      - network
      - network-bind
      - audio-playback
      - x11

parts:
  ajgui:
    plugin: dump
    source: https://github.com/applejuicenetz/gui-java/releases/download/$SNAPCRAFT_PROJECT_VERSION/AJCoreGUI.zip
    organize:
      '*': app/

  jre:
    plugin: nil
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-21-jre
    stage-packages:
      - openjdk-21-jre
      - x11-utils
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-21-openjdk-*/lib/security/blacklisted.certs

  launcher:
    plugin: dump
    source: ./snap/local/
    organize:
      '*': $SNAP/app/
